try conditions after failed step

diff --git a/.github/workflows/github_actions_test.yml b/.github/workflows/github_actions_test.yml
--- a/.github/workflows/github_actions_test.yml
+++ b/.github/workflows/github_actions_test.yml
@@ -22,28 +22,36 @@ jobs:
 #        run: |
 #          echo "This job is supposed to fail but workflow run should still be successful."
 #          dksjfhkd
-#  try-step-outcomes:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Successful step
-#        id: successful-step
-#        run: echo "Successful step"
-#      - name: Evaluate Successful step's success
-#        if: steps.successful-step.outcome == 'success'
-#        run: echo "Successful step's success outcome properly detected"
-#      - name: Evaluate Successful step's failure
-#        if: steps.successful-step.outcome == 'failure'
-#        run: echo "If this is printed step outcome of Successful step wasn't detected properly!"
-#      - name: Failed step
-#        id: failed-step
-#        run: sdkfljsdf
-#      - name: Evaluate Failed step's success
+  try-step-outcomes:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Successful step
+        id: successful-step
+        run: echo "Successful step"
+      - name: Evaluate Successful step's success
+        if: steps.successful-step.outcome == 'success'
+        run: echo "Successful step's success outcome properly detected"
+      - name: Evaluate Successful step's failure
+        if: steps.successful-step.outcome == 'failure'
+        run: echo "If this is printed step outcome of Successful step wasn't detected properly!"
+      - name: Failed step
+        id: failed-step
+        run: sdkfljsdf
+      - name: Step following failed step
+        if: success() || failure()
+        run: echo "This line should be printed"
+      - name: Important step following success/failure condition
+        run: echo "This line should be printed"
+      - name: One more step to be sure
+        run: echo "This line should be printed"
+  #      - name: Evaluate Failed step's success
 #        if: always() && steps.failed-step.outcome == 'success'
 #        run: echo "If this is printed step outcome of Failed step wasn't detected properly!"
 #      - name: Evaluate Failed step's failure
 #        if: always() && steps.failed-step.outcome == 'failure'
 #        run: echo "Failed step's failure outcome properly detected."
   notify-teams:
+    if: false # disabled for now
     uses: ./.github/workflows/reusable_notify_teams.yml
     with:
       stage: dev
